const SHEEP_GAIN_FROM_FOOD = 10
const WOLF_GAIN_FROM_FOOD = 20
const SHEEP_REPRODUCE = 0.05
const WOLF_SENSE_RADIUS = 15
const WOLF_REPRODUCE = 0.3
const MAX_SHEEP = 6000
const STARTING_SHEEP = 50
const STARTING_WOLVES = 20

const WIDTH = 800
const HEIGHT = 600

export {
    STARTING_SHEEP,
    SHEEP_GAIN_FROM_FOOD,
    SHEEP_REPRODUCE,
    MAX_SHEEP,
    STARTING_WOLVES,
    WOLF_GAIN_FROM_FOOD,
    WOLF_REPRODUCE,
    WOLF_SENSE_RADIUS,
    WIDTH,
    HEIGHT,
}
